project:
  type: website
  output-dir: docs
author: 
  - Helder Lira
website:
  title: "Laura Acevedo (análises)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


